pre-commit update

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,24 +1,76 @@
 #!/bin/sh
 
+# nest_core
+
 echo "🔍 Linting nest_core..."
-npm --prefix nest_core run lint || exit 1
+output=$(npm --prefix nest_core run lint 2>&1)
+status=$?
+if [ $status -ne 0 ]; then
+  echo "❌ Lint failed in nest_core"
+  echo "$output"
+  exit $status
+fi
 
 echo "🧪 Running tests in nest_core..."
-npm --prefix nest_core run test:e2e || exit 1
+output=$(npm --prefix nest_core run test:e2e 2>&1)
+status=$?
+if [ $status -ne 0 ]; then
+  echo "❌ Test failed in nest_core"
+  echo "$output"
+  exit $status
+fi
+
+# nest_mailer
 
 echo "🔍 Linting nest_mailer..."
-npm --prefix nest_mailer run lint || exit 1
+output=$(npm --prefix nest_mailer run lint 2>&1)
+status=$?
+if [ $status -ne 0 ]; then
+  echo "❌ Lint failed in nest_mailer"
+  echo "$output"
+  exit $status
+fi
+
+# next
 
 echo "🔍 Linting next..."
-npm --prefix next run lint:fix || exit 1
+output=$(npm --prefix next run lint:fix 2>&1)
+status=$?
+if [ $status -ne 0 ]; then
+  echo "❌ Lint failed in next"
+  echo "$output"
+  exit $status
+fi
 
 echo "🧪 Running tests in next..."
-npm --prefix next run test || exit 1
+output=$(npm --prefix next run test 2>&1)
+status=$?
+if [ $status -ne 0 ]; then
+  echo "❌ Test failed in next"
+  echo "$output"
+  exit $status
+fi
+
+# nuxt
 
 echo "🔍 Linting nuxt..."
-npm --prefix nuxt run lint:fix || exit 1
+output=$(npm --prefix nuxt run lint:fix 2>&1)
+status=$?
+if [ $status -ne 0 ]; then
+  echo "❌ Lint failed in nuxt"
+  echo "$output"
+  exit $status
+fi
 
 echo "🧪 Running tests in nuxt..."
-npm --prefix nuxt run test || exit 1
+output=$(npm --prefix nuxt run test:ci 2>&1)
+status=$?
+if [ $status -ne 0 ]; then
+  echo "❌ Test failed in nuxt"
+  echo "$output"
+  exit $status
+fi
+
+# final
 
 echo "✅ All checks passed!"
